#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Hubs,  S4, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CCustom)
#pragma config(Sensor, S3,     ,               sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_Matrix_S1_1, motor1,        tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S1_2, motor2,        tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S1_3, motor3,        tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S1_4, motor4,        tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S4_1, motor5,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S4_2, motor6,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S4_3, motor7,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S4_4, motor8,        tmotorMatrix, openLoop, reversed)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S4_1, servo5,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S4_2, servo6,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S4_3, servo7,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S4_4, servo8,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// motor 6 is the right auxilary motor, motor5 is the left auxilary motor

// include drivers
#include "JoystickDriver.c"        // Include file to handle the Bluetooth messages
#include "OmniWheelDriver.h"       // Include driver for the sensor multiplexer
#include "FTCtools.h"              // Include some usefull scripts
#include "hitechnic-compass.h"     // Include compass sensor file
#include "hitechnic-irseeker-v2.h" // Include driver for the IR Seeker V2
#include "lego-light.h"            // Include driver for the light sensors
#include "lego-touch.h"            // Include driver for the touch sensors

#define rTch			msensor_S2_2
#define lTch			msensor_S2_3

int rMtr = motor8; //motor8 is right motor, motor7 is left motor
int lMtr = motor7;

int target = 0;

task main()
{
	nMotorEncoder[rMtr] = 0;  // clear the encoders in the right
  nMotorEncoder[lMtr] = 0;	// and left motor

	while(true) {
		eraseDisplay();
		nxtDisplayString(0, "Btn: %d", nNxtButtonPressed);
		nxtDisplayString(1, "rMtr: %d", nMotorEncoder[rMtr]);
		nxtDisplayString(2, "lMtr: %d", nMotorEncoder[lMtr]);
		nxtDisplayString(3, "target: %d", target);
		nxtDisplayString(4, "lTch: %d", TSreadState(lTch));

		int rPress = TSreadState(rTch);
		int lPress = TSreadState(lTch);

		if(rPress) {nMotorEncoder[rMtr] = 0;}
		if(lPress) {nMotorEncoder[lMtr] = 0;}

		if(nNxtButtonPressed==2) {
			if(!rPress) {motor[rMtr]=-100;}else{motor[rMtr]=0;}
			if(!lPress) {motor[lMtr]=-100;}else{motor[lMtr]=0;}
			target = constraini(max2(nMotorEncoder[rMtr], nMotorEncoder[lMtr]), 0, 20000);
		} else if(nNxtButtonPressed==1) {
			motor[rMtr] = 100;
			motor[lMtr] = 100;
			target = constraini(max2(nMotorEncoder[rMtr], nMotorEncoder[lMtr]), 0, 20000);
		} else {
			motor[rMtr] = 0;
			motor[lMtr] = 0;

			if((target-75)>nMotorEncoder[rMtr]){motor[rMtr] = constraini(abs(nMotorEncoder[rMtr]-target)/30, 45, 100);}
			if((target-75)>nMotorEncoder[lMtr]){motor[lMtr] = constraini(abs(nMotorEncoder[rMtr]-target)/30, 45, 100);}

			if(((target+75)<nMotorEncoder[rMtr])&&(!rPress)){motor[rMtr] = -constraini(abs(nMotorEncoder[rMtr]-target)/30, 30, 100);}
			if(((target+75)<nMotorEncoder[lMtr])&&(!lPress)){motor[lMtr] = -constraini(abs(nMotorEncoder[rMtr]-target)/30, 30, 100);}
		}

	  //if(target>nMotorEncoder[rMtr]){motor[rMtr] = 30;}//else{motor[rMtr] = 0;}
		//if(target>nMotorEncoder[lMtr]){motor[lMtr] = 30;}//else{motor[lMtr] = 0;}

		//if(target>nMotorEncoder[rMtr]){motor[rMtr] = 100;}else{if(!rPress){motor[rMtr] = -100;}}
		//if(target>nMotorEncoder[lMtr]){motor[lMtr] = 100;}else{if(!lPress){motor[lMtr] = -100;}}

		//wait1Msec(2);
	}
}
