#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Hubs,  S4, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CCustom)
#pragma config(Sensor, S3,     ,               sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_Matrix_S1_1, motor1,        tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S1_2, motor2,        tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S1_3, motor3,        tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S1_4, motor4,        tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S4_1, motor5,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S4_2, motor6,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S4_3, motor7,        tmotorMatrix, PIDControl)
#pragma config(Motor,  mtr_Matrix_S4_4, motor8,        tmotorMatrix, PIDControl, reversed)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S4_1, servo5,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S4_2, servo6,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S4_3, servo7,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S4_4, servo8,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while(true) {
		motor[motor1] = 100;
		motor[motor2] = 100;
		motor[motor3] = 100;
		motor[motor4] = 100;
	}
}
