#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Hubs,  S2, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S3,     ,               sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorI2CCustom)
#pragma config(Motor,  mtr_Matrix_S1_1, motor1,        tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S1_2, motor2,        tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S1_3, motor3,        tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S1_4, motor4,        tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S2_1, motor5,        tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S2_2, motor6,        tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S2_3, motor7,        tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S2_4, motor8,        tmotorMatrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoStandard)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoStandard)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoStandard)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoStandard)
#pragma config(Servo,  srvo_Matrix_S2_1, servo5,               tServoStandard)
#pragma config(Servo,  srvo_Matrix_S2_2, servo6,               tServoStandard)
#pragma config(Servo,  srvo_Matrix_S2_3, servo7,               tServoStandard)
#pragma config(Servo,  srvo_Matrix_S2_4, servo8,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// servo 2 is claw servo
// servo 3 is IR servo

// include drivers
#include "JoystickDriver.c"        // Include file to handle the Bluetooth messages
#include "OmniWheelDriver.h"       // Include driver for the sensor multiplexer
#include "FTCtools.h"              // Include some usefull scripts
#include "hitechnic-compass.h"     // Include compass sensor file
#include "hitechnic-irseeker-v2.h" // Include driver for the IR Seeker V2
#include "lego-light.h"            // Include driver for the light sensors
#include "lego-touch.h"            // Include driver for the touch sensors

int rMtr = motor8; //motor8 is right motor, motor7 is left motor
int lMtr = motor7;

int servPos = 0;

task main()
{
	while(true) {
		eraseDisplay();
		nxtDisplayString(0, "Btn: %d", nNxtButtonPressed);
		nxtDisplayString(1, "serv0: %d", servPos);
		motor[lMtr] = 0;
		motor[rMtr] = 0;
		if(nNxtButtonPressed==2) {servPos -= 1; nxtDisplayString(2, "Backward");} else
		if(nNxtButtonPressed==1) {servPos += 1; nxtDisplayString(2, "Forward");}

		servPos = constraini(servPos, 0, 255);
		servo[servo3] = servPos;

		wait1Msec(10);
	}
}
